name: Build TensorFlow Lite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bazel
      run: |
        sudo apt update
        sudo apt install curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update
        sudo apt install bazel

    - name: Clone TensorFlow repository
      run: |
        git clone https://github.com/tensorflow/tensorflow.git -b v2.4.1 --depth 1
        cd tensorflow

    - name: Build TensorFlow Lite
      run: |
        cd tensorflow
        bazel build -c opt //tensorflow/lite:libtensorflowlite.so

    - name: Tar TensorFlow Lite and Core Util
      run: |
        cd tensorflow
        mkdir -p output
        tar -hczf output/tensorflow_lite.tar.gz -C tensorflow/lite .
        tar -hczf output/core_util.tar.gz -C tensorflow/core/util .
        cp bazel-bin/tensorflow/lite/libtensorflowlite.so output/.

    - name: Tar Flatbuffers
      run: |
        cd tensorflow/bazel-out/k8-opt/bin/external/flatbuffers/_virtual_includes/flatbuffers
        tar -hczf ../../../../../../../output/flatbuffers.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tensorflow-lite-headers-and-library
        path: tensorflow/output/
